### ISSUE TITLE
-Pagina de  "Diseño de paginas Web".

### ISSUE THREAD

**Issue by LuciaL152** [LuciaL152/MLG-MarketingDigital#11]
Crear la pagina "Diseño de paginas Web" con html y css , incluir mismo logo , mismo color de fuente en la barra de navegación y mismo footer que todas las demás paginas ..el contenido de la pagina puede ser de temática libre siguiendo igualmente el patrón del marketing digital.

**Comment by MicaelaOcampos** [comment]
Tarea realizada.
